spring:
  application:
    name: jrebel-license-server

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,liveness,readiness
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

server:
  port: 8080